is_production: false

doris:
  host: "10.6.129.242"
  port: 9030
  user: "root"
  password: ""

redis:
  host: "10.6.129.242"
  port: 6379
  password: "123456"

celery:
  broker_url : "redis://:123456@10.6.129.242:6379/0"
  result_backend : "redis://:123456@10.6.129.242:6379/1"
  enable_utc : False
  timezone : "Asia/Shanghai"